/* eslint-disable */
/**
 * Generated by clients/typescript/scripts/codegen.ts from
 * pkg/sextantproto/schemas/wire.json (itself generated from the Go
 * source of truth in pkg/sextantproto).
 *
 * DO NOT EDIT by hand — re-run `npm run codegen` (or `go generate
 * ./...`) after the Go wire constants change.
 */

/** Envelope protocol version emitted by this client (matches Go ProtoVersion). */
export const PROTO_VERSION = "0.5.0";

/**
 * WireEpoch — the machine-checked bus compatibility key (RFC §5.8).
 * Matches Go sextantproto.WireEpoch; the CI schema-compat gate fails a
 * breaking wire change that did not bump it.
 */
export const WIRE_EPOCH = 2;

// Recognized envelope kinds. Mirrors sextantproto.Kind.
export const KIND_AGENT_FRAME = "agent_frame";
export const KIND_LIFECYCLE = "lifecycle";
export const KIND_AUDIT = "audit";
export const KIND_TELEMETRY_SPAN = "telemetry_span";
export const KIND_TELEMETRY_METRIC = "telemetry_metric";
export const KIND_TELEMETRY_LOG = "telemetry_log";
export const KIND_USER_INPUT_REQUEST = "user_input_request";
export const KIND_USER_INPUT_RESPONSE = "user_input_response";
export const KIND_RPC_REQUEST = "rpc_request";
export const KIND_RPC_RESPONSE = "rpc_response";
export const KIND_HEARTBEAT = "heartbeat";

// Recognized Address kinds. Mirrors sextantproto.AddressKind.
export const ADDRESS_AGENT = "agent";
export const ADDRESS_OPERATOR = "operator";
export const ADDRESS_DAEMON = "daemon";
export const ADDRESS_UI = "ui";
export const ADDRESS_EXTERNAL = "external";

// Recognized agent frame kinds. Mirrors sextantproto.FrameKind.
export const FRAME_ASSISTANT_TEXT = "assistant_text";
export const FRAME_TOOL_CALL = "tool_call";
export const FRAME_TOOL_RESULT = "tool_result";
export const FRAME_SYSTEM_NOTE = "system_note";
export const FRAME_ERROR = "error";

/** Every recognized AddressKind, for membership checks. */
export const ADDRESS_KINDS = ["agent","operator","daemon","ui","external"] as const;
