/* eslint-disable */
/**
 * Generated by clients/typescript/scripts/codegen.ts.
 * DO NOT EDIT by hand — re-run `npm run codegen` after the source
 * JSON Schemas under pkg/sextantproto/schemas/ change.
 */

/**
 * UUID (canonical lowercase string form on the wire).
 *
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "UUID".
 */
export type UUID = string;
/**
 * RFC 3339 timestamp with microsecond precision (matches Go sextantproto.Timestamp).
 *
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Timestamp".
 */
export type Timestamp = string;

export interface SextantProtoBundle {}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Address".
 */
export interface Address {
  kind: string;
  id: string;
  host?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentDefinition".
 */
export interface AgentDefinition {
  uuid: UUID;
  name: string;
  type: string;
  template?: string;
  runtime: RuntimeConfig;
  sandbox: SandboxConfig;
  tools?: string[];
  host_pin?: string;
  lifecycle: string;
  current_incarnation_id?: UUID;
  version: number;
  created_at: Timestamp;
  updated_at: Timestamp;
  escalate_to?: string;
  description?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RuntimeConfig".
 */
export interface RuntimeConfig {
  model: string;
  provider?: string;
  params?: {
    [k: string]: string | undefined;
  };
  permission_mode?: string;
  session_id?: string;
  initial_prompt?: string;
  permission_ceiling?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SandboxConfig".
 */
export interface SandboxConfig {
  image: string;
  mounts?: string[];
  env?: {
    [k: string]: string | undefined;
  };
  credentials?: string[];
  resource_limits?: ResourceLimits;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ResourceLimits".
 */
export interface ResourceLimits {
  cpu_shares?: number;
  memory_mib?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentFramePayload".
 */
export interface AgentFramePayload {
  frame_kind: string;
  session_id?: string;
  tool_name?: string;
  body: {};
  tokens?: FrameTokens;
  tags?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "FrameTokens".
 */
export interface FrameTokens {
  input: number;
  output: number;
  cache_read?: number;
  cache_created?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentIncarnation".
 */
export interface AgentIncarnation {
  incarnation_id: UUID;
  agent_uuid: UUID;
  started_at: Timestamp;
  ended_at?: Timestamp;
  host_id: string;
  container_id?: string;
  state: string;
  exit_code?: number;
  jwt_key_id?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ArchiveAgentRequest".
 */
export interface ArchiveAgentRequest {
  agent_id: UUID;
  grace_seconds?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ArchiveAgentResponse".
 */
export interface ArchiveAgentResponse {
  ok: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AuditPayload".
 */
export interface AuditPayload {
  actor: string;
  agent_uuid?: UUID;
  action: string;
  capability_required?: string;
  result: string;
  details?: {};
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Envelope".
 */
export interface Envelope {
  id: UUID;
  ts: Timestamp;
  proto_version: string;
  from: Address;
  to?: Address;
  trace_id: UUID;
  span_id: UUID;
  parent_span_id?: UUID;
  idempotency_key?: string;
  reply_to?: string;
  kind: string;
  payload: unknown;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ExecInContainerRequest".
 */
export interface ExecInContainerRequest {
  agent_id: UUID;
  cmd: string[];
  workdir?: string;
  env?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ExecInContainerResponse".
 */
export interface ExecInContainerResponse {
  stdout: string;
  stderr: string;
  exit_code: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "GetAgentStatusRequest".
 */
export interface GetAgentStatusRequest {
  agent_id: UUID;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentStatus".
 */
export interface AgentStatus {
  uuid: UUID;
  name: string;
  lifecycle: string;
  version: number;
  updated_at: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "GetAgentStatusResponse".
 */
export interface GetAgentStatusResponse {
  status: AgentStatus;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "HeartbeatPayload".
 */
export interface HeartbeatPayload {
  agent_uuid: UUID;
  incarnation_id: UUID;
  host_id: string;
  uptime_seconds: number;
  last_frame_ts?: Timestamp;
  pending_prompts?: number;
  resource_usage?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "KillAgentRequest".
 */
export interface KillAgentRequest {
  agent_id: UUID;
  grace_seconds?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "KillAgentResponse".
 */
export interface KillAgentResponse {
  ok: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "LifecyclePayload".
 */
export interface LifecyclePayload {
  incarnation_id: UUID;
  agent_uuid: UUID;
  transition: string;
  state: string;
  reason?: string;
  exit_code?: number;
  source?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListAgentsFilter".
 */
export interface ListAgentsFilter {
  lifecycle?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListAgentsRequest".
 */
export interface ListAgentsRequest {
  filter?: ListAgentsFilter;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentSummary".
 */
export interface AgentSummary {
  uuid: UUID;
  name: string;
  type?: string;
  template?: string;
  lifecycle: string;
  version: number;
  updated_at: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListAgentsResponse".
 */
export interface ListAgentsResponse {
  agents: AgentSummary[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListDirRequest".
 */
export interface ListDirRequest {
  agent_id: UUID;
  path: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListDirEntry".
 */
export interface ListDirEntry {
  name: string;
  is_dir: boolean;
  size?: number;
  mode?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListDirResponse".
 */
export interface ListDirResponse {
  entries: ListDirEntry[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "LogRecord".
 */
export interface LogRecord {
  timestamp_ns: number;
  observed_timestamp_ns?: number;
  trace_id?: string;
  span_id?: string;
  severity_text?: string;
  severity_number?: number;
  service_name: string;
  body: string;
  resource_attributes?: {
    [k: string]: string | undefined;
  };
  log_attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Metric".
 */
export interface Metric {
  timestamp_ns: number;
  metric_name: string;
  metric_description?: string;
  metric_unit?: string;
  metric_type: string;
  service_name: string;
  resource_attributes?: {
    [k: string]: string | undefined;
  };
  attributes?: {
    [k: string]: string | undefined;
  };
  value: number;
  count?: number;
  sum?: number;
  bucket_counts?: number[];
  explicit_bounds?: number[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "PromptAgentRequest".
 */
export interface PromptAgentRequest {
  agent_id: UUID;
  content: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "PromptAgentResponse".
 */
export interface PromptAgentResponse {
  ok: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryAuditFilter".
 */
export interface QueryAuditFilter {
  actor?: string;
  action?: string;
  agent_uuid?: UUID;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryAuditRequest".
 */
export interface QueryAuditRequest {
  filter: QueryAuditFilter;
  time_range: TimeRange;
  limit?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "TimeRange".
 */
export interface TimeRange {
  since?: string;
  until?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryAuditResponse".
 */
export interface QueryAuditResponse {
  rows: QueryAuditRow[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryAuditRow".
 */
export interface QueryAuditRow {
  id: UUID;
  ts: string;
  actor: string;
  agent_uuid: UUID;
  action: string;
  capability_required: string;
  result: string;
  payload: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryHistoryFilter".
 */
export interface QueryHistoryFilter {
  subject?: string;
  from_id?: string;
  agent_uuid?: UUID;
  kind?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryHistoryRequest".
 */
export interface QueryHistoryRequest {
  filter: QueryHistoryFilter;
  time_range: TimeRange;
  limit?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryHistoryResponse".
 */
export interface QueryHistoryResponse {
  events: Envelope[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryTraceRequest".
 */
export interface QueryTraceRequest {
  trace_id: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryTraceResponse".
 */
export interface QueryTraceResponse {
  spans: TraceSpan[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "TraceSpan".
 */
export interface TraceSpan {
  trace_id: string;
  span_id: string;
  parent_span_id?: string;
  span_name: string;
  span_kind: string;
  service_name: string;
  timestamp: string;
  duration_nanos: number;
  status_code?: string;
  status_message?: string;
  attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ReadFileRequest".
 */
export interface ReadFileRequest {
  agent_id: UUID;
  path: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ReadFileResponse".
 */
export interface ReadFileResponse {
  content: string;
  content_type: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RestartAgentRequest".
 */
export interface RestartAgentRequest {
  agent_id: UUID;
  preserve_session?: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RestartAgentResponse".
 */
export interface RestartAgentResponse {
  agent_id: UUID;
  ok: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RPCError".
 */
export interface RPCError {
  code: string;
  message: string;
  details?: {};
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RPCRequest".
 */
export interface RPCRequest {
  verb: string;
  args: unknown;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RPCResponse".
 */
export interface RPCResponse {
  result?: unknown;
  error?: RPCError;
  _terminal: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Span".
 */
export interface Span {
  timestamp_ns: number;
  trace_id: string;
  span_id: string;
  parent_span_id?: string;
  trace_state?: string;
  span_name: string;
  span_kind: string;
  service_name: string;
  resource_attributes?: {
    [k: string]: string | undefined;
  };
  span_attributes?: {
    [k: string]: string | undefined;
  };
  duration_ns: number;
  status_code: string;
  status_message?: string;
  events?: SpanEvent[];
  links?: SpanLink[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SpanEvent".
 */
export interface SpanEvent {
  timestamp_ns: number;
  name: string;
  attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SpanLink".
 */
export interface SpanLink {
  trace_id: string;
  span_id: string;
  trace_state?: string;
  attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SpawnAgentRequest".
 */
export interface SpawnAgentRequest {
  name: string;
  template: string;
  host_pin?: string;
  definition_overrides?: {};
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SpawnAgentResponse".
 */
export interface SpawnAgentResponse {
  agent_id: UUID;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "StatRequest".
 */
export interface StatRequest {
  agent_id: UUID;
  path: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "StatResponse".
 */
export interface StatResponse {
  name: string;
  size: number;
  mode: string;
  is_dir: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "UserInputRequestPayload".
 */
export interface UserInputRequestPayload {
  request_id: UUID;
  from_uuid: UUID;
  question: string;
  options?: string[];
  urgency?: string;
  group_with?: UUID;
  context?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "UserInputResponsePayload".
 */
export interface UserInputResponsePayload {
  request_id: UUID;
  decision: string;
  answer?: string;
  escalate_to?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeCreateRequest".
 */
export interface WorktreeCreateRequest {
  name: string;
  base_branch?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeCreateResponse".
 */
export interface WorktreeCreateResponse {
  worktree: WorktreeInfo;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeInfo".
 */
export interface WorktreeInfo {
  name: string;
  path: string;
  branch: string;
  base_branch: string;
  owning_agent?: UUID;
  status: string;
  created_at: string;
  last_activity: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeDestroyRequest".
 */
export interface WorktreeDestroyRequest {
  name: string;
  force?: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeDestroyResponse".
 */
export interface WorktreeDestroyResponse {
  ok: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeDiffRequest".
 */
export interface WorktreeDiffRequest {
  name: string;
  against?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeDiffResponse".
 */
export interface WorktreeDiffResponse {
  diff: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeListRequest".
 */
export interface WorktreeListRequest {}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeListResponse".
 */
export interface WorktreeListResponse {
  worktrees: WorktreeInfo[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeMergeRequest".
 */
export interface WorktreeMergeRequest {
  name: string;
  target?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "WorktreeMergeResponse".
 */
export interface WorktreeMergeResponse {
  ok: boolean;
  branch?: string;
  target?: string;
  conflicts?: string[];
}
