/* eslint-disable */
/**
 * Generated by clients/typescript/scripts/codegen.ts.
 * DO NOT EDIT by hand — re-run `npm run codegen` after the source
 * JSON Schemas under pkg/sextantproto/schemas/ change.
 */

/**
 * UUID (canonical lowercase string form on the wire).
 *
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "UUID".
 */
export type UUID = string;
/**
 * RFC 3339 timestamp with microsecond precision (matches Go sextantproto.Timestamp).
 *
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Timestamp".
 */
export type Timestamp = string;

export interface SextantProtoBundle {}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Address".
 */
export interface Address {
  kind: string;
  id: string;
  host?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentDefinition".
 */
export interface AgentDefinition {
  uuid: UUID;
  name: string;
  type: string;
  template?: string;
  runtime: RuntimeConfig;
  sandbox: SandboxConfig;
  tools?: string[];
  host_pin?: string;
  lifecycle: string;
  version: number;
  created_at: Timestamp;
  updated_at: Timestamp;
  escalate_to?: string;
  description?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RuntimeConfig".
 */
export interface RuntimeConfig {
  model: string;
  provider?: string;
  params?: {
    [k: string]: string | undefined;
  };
  permission_mode?: string;
  session_id?: string;
  initial_prompt?: string;
  permission_ceiling?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SandboxConfig".
 */
export interface SandboxConfig {
  image: string;
  mounts?: string[];
  env?: {
    [k: string]: string | undefined;
  };
  credentials?: string[];
  resource_limits?: ResourceLimits;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ResourceLimits".
 */
export interface ResourceLimits {
  cpu_shares?: number;
  memory_mib?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentFramePayload".
 */
export interface AgentFramePayload {
  frame_kind: string;
  session_id?: string;
  tool_name?: string;
  body: {};
  tokens?: FrameTokens;
  tags?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "FrameTokens".
 */
export interface FrameTokens {
  input: number;
  output: number;
  cache_read?: number;
  cache_created?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentIncarnation".
 */
export interface AgentIncarnation {
  incarnation_id: UUID;
  agent_uuid: UUID;
  started_at: Timestamp;
  ended_at?: Timestamp;
  host_id: string;
  container_id?: string;
  state: string;
  exit_code?: number;
  jwt_key_id?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AuditPayload".
 */
export interface AuditPayload {
  actor: string;
  agent_uuid?: UUID;
  action: string;
  capability_required?: string;
  result: string;
  details?: {};
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Envelope".
 */
export interface Envelope {
  id: UUID;
  ts: Timestamp;
  proto_version: string;
  from: Address;
  to?: Address;
  trace_id: UUID;
  span_id: UUID;
  parent_span_id?: UUID;
  idempotency_key?: string;
  reply_to?: string;
  kind: string;
  payload: unknown;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "GetAgentStatusRequest".
 */
export interface GetAgentStatusRequest {
  agent_id: UUID;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentStatus".
 */
export interface AgentStatus {
  uuid: UUID;
  name: string;
  lifecycle: string;
  version: number;
  updated_at: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "GetAgentStatusResponse".
 */
export interface GetAgentStatusResponse {
  status: AgentStatus;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "HeartbeatPayload".
 */
export interface HeartbeatPayload {
  agent_uuid: UUID;
  incarnation_id: UUID;
  host_id: string;
  uptime_seconds: number;
  last_frame_ts?: Timestamp;
  pending_prompts?: number;
  resource_usage?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "LifecyclePayload".
 */
export interface LifecyclePayload {
  incarnation_id: UUID;
  agent_uuid: UUID;
  transition: string;
  state: string;
  reason?: string;
  exit_code?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListAgentsFilter".
 */
export interface ListAgentsFilter {
  lifecycle?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListAgentsRequest".
 */
export interface ListAgentsRequest {
  filter?: ListAgentsFilter;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "AgentSummary".
 */
export interface AgentSummary {
  uuid: UUID;
  name: string;
  type?: string;
  template?: string;
  lifecycle: string;
  version: number;
  updated_at: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ListAgentsResponse".
 */
export interface ListAgentsResponse {
  agents: AgentSummary[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "LogRecord".
 */
export interface LogRecord {
  timestamp_ns: number;
  observed_timestamp_ns?: number;
  trace_id?: string;
  span_id?: string;
  severity_text?: string;
  severity_number?: number;
  service_name: string;
  body: string;
  resource_attributes?: {
    [k: string]: string | undefined;
  };
  log_attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Metric".
 */
export interface Metric {
  timestamp_ns: number;
  metric_name: string;
  metric_description?: string;
  metric_unit?: string;
  metric_type: string;
  service_name: string;
  resource_attributes?: {
    [k: string]: string | undefined;
  };
  attributes?: {
    [k: string]: string | undefined;
  };
  value: number;
  count?: number;
  sum?: number;
  bucket_counts?: number[];
  explicit_bounds?: number[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryHistoryFilter".
 */
export interface QueryHistoryFilter {
  subject?: string;
  from_id?: string;
  agent_uuid?: UUID;
  kind?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryHistoryRequest".
 */
export interface QueryHistoryRequest {
  filter: QueryHistoryFilter;
  time_range: TimeRange;
  limit?: number;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "TimeRange".
 */
export interface TimeRange {
  since?: string;
  until?: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "QueryHistoryResponse".
 */
export interface QueryHistoryResponse {
  events: Envelope[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ReadFileRequest".
 */
export interface ReadFileRequest {
  agent_id: UUID;
  path: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "ReadFileResponse".
 */
export interface ReadFileResponse {
  content: string;
  content_type: string;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RPCError".
 */
export interface RPCError {
  code: string;
  message: string;
  details?: {};
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RPCRequest".
 */
export interface RPCRequest {
  verb: string;
  args: unknown;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "RPCResponse".
 */
export interface RPCResponse {
  result?: unknown;
  error?: RPCError;
  _terminal: boolean;
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "Span".
 */
export interface Span {
  timestamp_ns: number;
  trace_id: string;
  span_id: string;
  parent_span_id?: string;
  trace_state?: string;
  span_name: string;
  span_kind: string;
  service_name: string;
  resource_attributes?: {
    [k: string]: string | undefined;
  };
  span_attributes?: {
    [k: string]: string | undefined;
  };
  duration_ns: number;
  status_code: string;
  status_message?: string;
  events?: SpanEvent[];
  links?: SpanLink[];
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SpanEvent".
 */
export interface SpanEvent {
  timestamp_ns: number;
  name: string;
  attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "SpanLink".
 */
export interface SpanLink {
  trace_id: string;
  span_id: string;
  trace_state?: string;
  attributes?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "UserInputRequestPayload".
 */
export interface UserInputRequestPayload {
  request_id: UUID;
  from_uuid: UUID;
  question: string;
  options?: string[];
  urgency?: string;
  group_with?: UUID;
  context?: {
    [k: string]: string | undefined;
  };
}
/**
 * This interface was referenced by `SextantProtoBundle`'s JSON-Schema
 * via the `definition` "UserInputResponsePayload".
 */
export interface UserInputResponsePayload {
  request_id: UUID;
  decision: string;
  answer?: string;
  escalate_to?: string;
}
