// lexgen generates the TypeScript record types for the goals convention from the
// goal lexicon (protocol/lexicons/goal.json) — the TS half of ADR-0041's "record
// types are generated from the lexicon per language". It is the peer of the Go
// generator (clients/go/conventions/goals/internal/lexgen): both read the SAME
// lexicon and emit the SAME field names, so the two languages cannot drift from
// the contract.
//
// It is deliberately NOT a universal lexicon→TS engine. It generates exactly the
// goal records: the goal record's object and its one nested object-array
// (criteria → Criterion). The bright line is "concept, not codegen" — only the
// record TYPES are generated; the verb LOGIC in src/goals.ts is hand-written. A
// second convention that needs generated types gets its own small generator (or
// this one generalised against that real second case), not a speculative engine.
//
// Run it with `npm run generate` (which runs `node tools/lexgen.ts`; Node strips
// the TS types). The output is src/goal_gen.ts, committed, with a generated-file
// header naming this tool and the source lexicon so a fresh reader knows not to
// hand-edit it and where it comes from.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// The goals package dir (this file lives in tools/ beneath it).
const pkgDir = dirname(dirname(fileURLToPath(import.meta.url)));
// The goal lexicon, relative to the package dir: up to the repo root, then into
// protocol/lexicons. (clients/ts/conventions/goals → repo root is four up.)
const lexiconFile = join(pkgDir, "..", "..", "..", "..", "protocol", "lexicons", "goal.json");
// The generated types file, in the package's src dir.
const outputFile = join(pkgDir, "src", "goal_gen.ts");

// --- lexicon parsing (the goal record def) ---

// ObjectDef is a lexicon object: its required field set and its properties in
// authored order (order is preserved so the generated type reads like the
// lexicon).
interface ObjectDef {
  required: Set<string>;
  props: Property[];
}

interface Property {
  name: string;
  typ: string; // lexicon type: "string", "array", "object"
  desc: string; // the lexicon description, carried onto the field as a doc comment
  item?: ObjectDef; // for type=="array" of objects: the item object def
}

// parseRecord extracts the goal record def (defs.main.record) into an ObjectDef.
function parseRecord(raw: string): ObjectDef {
  const lf = JSON.parse(raw) as {
    defs?: { main?: { record?: unknown } };
  };
  const record = lf.defs?.main?.record;
  if (!record || typeof record !== "object") {
    throw new Error("lexgen: goal lexicon has no defs.main.record object");
  }
  return parseObject(record as Record<string, unknown>);
}

// parseObject decodes one lexicon object def: its required set and ordered
// properties. JS preserves object key insertion order for string keys, so the
// generated fields mirror the authored order in the JSON file.
function parseObject(od: Record<string, unknown>): ObjectDef {
  const required = new Set<string>((od["required"] as string[] | undefined) ?? []);
  const properties = (od["properties"] as Record<string, unknown> | undefined) ?? {};
  const props: Property[] = [];
  for (const key of Object.keys(properties)) {
    const pv = properties[key] as { type?: string; description?: string; items?: unknown };
    const p: Property = { name: key, typ: pv.type ?? "", desc: pv.description ?? "" };
    if (pv.type === "array" && pv.items && typeof pv.items === "object") {
      const items = pv.items as Record<string, unknown>;
      if (items["type"] === "object") {
        p.item = parseObject(items);
      }
    }
    props.push(p);
  }
  return { required, props };
}

// --- rendering ---

// render emits the goal_gen.ts source: a Goal interface for the record and a
// Criterion interface for the criteria item, both with field names matching the
// lexicon exactly (the whole point — the types cannot drift from the contract).
// A non-required field is optional (`?`), the TS peer of Go's omitempty.
function render(rec: ObjectDef): string {
  let b = "";
  b += "// Code generated by clients/ts/conventions/goals/tools/lexgen.ts from\n";
  b += "// protocol/lexicons/goal.json. DO NOT EDIT.\n";
  b += "//\n";
  b += "// The record types are generated so they cannot silently drift from the\n";
  b += "// lexicon contract (ADR-0041) — the peer of the Go generator\n";
  b += "// (clients/go/conventions/goals/internal/lexgen). Regenerate with\n";
  b += "// `npm run generate` after editing the lexicon; the verb logic that uses\n";
  b += "// these types is hand-written in src/goals.ts.\n\n";

  // The criteria item type, if any, named by singularising the array field. It is
  // declared before the Goal type that references it.
  for (const p of rec.props) {
    if (p.item) {
      b += renderInterface(
        singular(p.name),
        "is one acceptance criterion of a goal (the criteria array item).",
        p.item,
      );
      b += "\n";
    }
  }
  b += renderInterface(
    "Goal",
    "is the goal record (protocol/lexicons/goal.json): a north-star plus its " +
      "acceptance criteria. Goal STATUS is derived from the criteria rollup, never " +
      "stored — see the read side in goals.ts.",
    rec,
  );
  return b;
}

// renderInterface writes one exported interface.
function renderInterface(name: string, doc: string, od: ObjectDef): string {
  let b = `// ${name} ${doc}\n`;
  b += `export interface ${name} {\n`;
  for (const p of od.props) {
    if (p.desc) {
      b += `  // ${oneLine(p.desc)}\n`;
    }
    const opt = od.required.has(p.name) ? "" : "?";
    b += `  ${tsField(p.name)}${opt}: ${tsType(p)};\n`;
  }
  b += "}\n";
  return b;
}

// tsType maps a lexicon property to its TS type. A string is string; an array of
// objects is an array of the singularised item type; any other array or an object
// falls back to a recursive JSON value (opaque), which keeps the generator minimal
// without dropping unknown shapes. The goal lexicon only exercises string and the
// criteria object-array today.
function tsType(p: Property): string {
  switch (p.typ) {
    case "string":
      return "string";
    case "array":
      if (p.item) {
        return `${singular(p.name)}[]`;
      }
      return "JsonValue[]";
    default:
      return "JsonValue";
  }
}

// tsField quotes a field name only if it is not a plain identifier. The goal
// lexicon uses simple single-word names, so this is the identity for them.
function tsField(field: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(field) ? field : JSON.stringify(field);
}

// singular turns an array field name into its item type name (criteria →
// Criterion). It handles the one irregular plural the goal lexicon uses and a
// simple trailing-s fallback; a richer pluraliser is unwarranted for one field.
function singular(field: string): string {
  if (field === "criteria") return "Criterion";
  const name = field.charAt(0).toUpperCase() + field.slice(1);
  return name.endsWith("s") ? name.slice(0, -1) : name;
}

// oneLine collapses a multi-line lexicon description to a single comment line.
function oneLine(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

function main(): void {
  const raw = readFileSync(lexiconFile, "utf8");
  const rec = parseRecord(raw);
  let src = render(rec);
  // The generated interfaces reference JsonValue for any opaque field; declare it
  // locally so the file is self-contained (no SDK import) and matches the lexicon's
  // "content is opaque" stance. Emit it only if used.
  if (src.includes("JsonValue")) {
    src =
      src +
      "\n" +
      "// JsonValue is an opaque JSON value, used for any lexicon field this generator\n" +
      "// does not model as a concrete type (the goal lexicon does not hit this today).\n" +
      "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n";
  }
  writeFileSync(outputFile, src);
  process.stderr.write(`lexgen: wrote ${outputFile}\n`);
}

main();
