package conformance

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	pconf "github.com/love-lena/sextant/protocol/conformance"
)

// update is the golden-file flag: `go test ./sdk/conformance -update`
// (re)records the vectors a registered verb produces, rather than asserting
// against them. It mirrors the repo's TUI golden convention. A vector is
// regenerated by running its verb against a Recorder and writing the captured
// transcript back over the file — so a deliberate verb change is a one-command
// re-record plus a reviewed diff, never a hand-edit.
var update = flag.Bool("update", false, "re-record conformance vectors from the registered verbs")

// Updating reports whether -update was passed. A convention suite that records
// its own sample vectors (or the fixture test here) checks it to branch between
// replay and record.
func Updating() bool { return *update }

// ReplayVectors discovers every op-transcript vector under dir for each
// convention the registry knows, runs the named verb against a Recorder, and
// asserts the captured operations equal the vector's, in order, under the
// canonical-JSON rule. dir is the vectors root (e.g.
// filepath.Join("..","..","protocol","conformance","vectors") from a test).
//
// With -update set it RE-RECORDS instead: it runs each verb and writes the
// captured transcript back over the vector file (preserving epoch, description,
// and input). A convention with vectors but no registered verb fails loudly —
// a vector no verb answers is a gap, not a pass. A registered convention with
// no vectors yet is fine (returns quietly): the seam exists before the vectors
// do, which is exactly the 183-before-173 ordering.
//
// Each vector runs as a subtest named by its path, so a failure points at the
// file. The optional opts let a convention seed recorder state per vector (a
// read-then-write verb needs a prior artifact value) — see ReplayOption.
func ReplayVectors(t *testing.T, dir string, reg *Registry, opts ...ReplayOption) {
	t.Helper()
	cfg := replayConfig{}
	for _, o := range opts {
		o(&cfg)
	}

	for _, conv := range reg.Conventions() {
		vectors, err := pconf.LoadOpTranscripts(dir, conv)
		if err != nil {
			t.Fatalf("load %q vectors: %v", conv, err)
		}
		for _, lv := range vectors {
			lv := lv
			t.Run(relName(dir, lv.Path), func(t *testing.T) {
				replayOne(t, reg, lv, cfg)
			})
		}
	}
}

func replayOne(t *testing.T, reg *Registry, lv pconf.LoadedOpTranscript, cfg replayConfig) {
	t.Helper()
	v := lv.Vector
	fn, ok := reg.Lookup(v.Convention, v.Verb)
	if !ok {
		t.Fatalf("vector %s names verb %s/%s, which is not registered", lv.Path, v.Convention, v.Verb)
	}

	rec := NewRecorder()
	if cfg.seed != nil {
		cfg.seed(rec, v)
	}
	if err := fn(context.Background(), rec, v.Input); err != nil {
		t.Fatalf("vector %s: verb %s/%s returned error: %v", lv.Path, v.Convention, v.Verb, err)
	}
	got := rec.Operations()

	if *update {
		rewriteVector(t, lv.Path, v, got)
		return
	}
	assertOpsEqual(t, lv.Path, v.Operations, got)
}

// rewriteVector writes the captured ops back over the vector file, keeping the
// vector's metadata (epoch, convention, verb, description, input) and replacing
// only operations. The output is pretty-printed JSON with a trailing newline —
// the on-disk form a human reviews — distinct from the canonical form used only
// for COMPARISON.
func rewriteVector(t *testing.T, path string, v pconf.OpTranscriptVector, got []pconf.Op) {
	t.Helper()
	v.Operations = got
	if err := writeJSONVector(path, v); err != nil {
		t.Fatalf("re-record %s: %v", path, err)
	}
	t.Logf("re-recorded %s (%d operations)", path, len(got))
}

// assertOpsEqual compares the recorded transcript to the expected one,
// order-sensitive, each operation's payload under the canonical-JSON rule. It
// reports the first divergence with both sides, so a failure reads as a diff.
func assertOpsEqual(t *testing.T, path string, want, got []pconf.Op) {
	t.Helper()
	if len(want) != len(got) {
		t.Errorf("%s: operation count: want %d, got %d\nwant: %s\ngot:  %s",
			path, len(want), len(got), opsSummary(want), opsSummary(got))
		return
	}
	for i := range want {
		w, g := want[i], got[i]
		if w.Op != g.Op {
			t.Errorf("%s: op[%d].op: want %q, got %q", path, i, w.Op, g.Op)
			continue
		}
		if w.Subject != g.Subject {
			t.Errorf("%s: op[%d] (%s).subject: want %q, got %q", path, i, w.Op, w.Subject, g.Subject)
		}
		if w.Name != g.Name {
			t.Errorf("%s: op[%d] (%s).name: want %q, got %q", path, i, w.Op, w.Name, g.Name)
		}
		if !revEqual(w.ExpectedRev, g.ExpectedRev) {
			t.Errorf("%s: op[%d] (%s).expectedRev: want %v, got %v", path, i, w.Op, derefRev(w.ExpectedRev), derefRev(g.ExpectedRev))
		}
		eq, err := pconf.CanonicalEqual(w.Payload, g.Payload)
		if err != nil {
			t.Errorf("%s: op[%d] (%s).payload canonicalize: %v", path, i, w.Op, err)
			continue
		}
		if !eq {
			cw, _ := pconf.Canonicalize(w.Payload)
			cg, _ := pconf.Canonicalize(g.Payload)
			t.Errorf("%s: op[%d] (%s).payload mismatch:\n want: %s\n got:  %s", path, i, w.Op, cw, cg)
		}
	}
}

// RecordVector runs a verb against a fresh Recorder and returns a vector ready
// to serialize — the recording half a convention's sample-vector generator (or
// a test's -update path) uses to produce a vector from code. The caller fills
// in any seeding via a Recorder it passes, or uses the no-seed form here.
func RecordVector(epoch int, convention, verb, description string, input json.RawMessage, fn Verb, seed func(*Recorder)) (pconf.OpTranscriptVector, error) {
	rec := NewRecorder()
	if seed != nil {
		seed(rec)
	}
	if err := fn(context.Background(), rec, input); err != nil {
		return pconf.OpTranscriptVector{}, fmt.Errorf("conformance: record %s/%s: %w", convention, verb, err)
	}
	return pconf.OpTranscriptVector{
		Epoch:       epoch,
		Convention:  convention,
		Verb:        verb,
		Description: description,
		Input:       input,
		Operations:  rec.Operations(),
	}, nil
}

// WriteVector serializes v to path in the human-reviewable pretty form (sorted
// metadata, trailing newline). It is what a convention's -update path calls
// after RecordVector to lay a sample vector down on disk.
func WriteVector(path string, v pconf.OpTranscriptVector) error {
	return writeJSONVector(path, v)
}

// writeJSONVector marshals v (an op-transcript or a wire vector) to path in the
// human-reviewable pretty form: two-space indent, trailing newline, parent dir
// created. This is the on-disk form a human reviews; the canonical form is used
// only for COMPARISON.
func writeJSONVector(path string, v any) error {
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return fmt.Errorf("conformance: marshal vector: %w", err)
	}
	out = append(out, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("conformance: mkdir for vector: %w", err)
	}
	return os.WriteFile(path, out, 0o644)
}

// replayConfig / ReplayOption configure ReplayVectors.
type replayConfig struct {
	seed func(*Recorder, pconf.OpTranscriptVector)
}

// ReplayOption tunes a replay run.
type ReplayOption func(*replayConfig)

// WithSeed installs a per-vector recorder-seeding hook: before each vector's
// verb runs, seed is called with the Recorder and the vector, so a read-then-
// write verb sees a realistic prior artifact value. The seed is recording
// setup, not part of the transcript.
func WithSeed(seed func(*Recorder, pconf.OpTranscriptVector)) ReplayOption {
	return func(c *replayConfig) { c.seed = seed }
}

func revEqual(a, b *uint64) bool {
	switch {
	case a == nil && b == nil:
		return true
	case a == nil || b == nil:
		return false
	default:
		return *a == *b
	}
}

func derefRev(p *uint64) any {
	if p == nil {
		return nil
	}
	return *p
}

func opsSummary(ops []pconf.Op) string {
	names := make([]string, len(ops))
	for i, o := range ops {
		names[i] = o.Op
	}
	b, _ := json.Marshal(names)
	return string(b)
}

func relName(dir, path string) string {
	if r, err := filepath.Rel(dir, path); err == nil {
		return r
	}
	return filepath.Base(path)
}
