// Code generated by conventions/goal/go/internal/lexgen from
// protocol/lexicons/goal.json. DO NOT EDIT.
//
// The record types are generated so they cannot silently drift from the
// lexicon contract (ADR-0041). Regenerate with `make generate` (or
// `go generate ./conventions/goal/go/...`) after editing the lexicon;
// the verb logic that uses these types is hand-written in goals.go.

package goals

// Criterion is one acceptance criterion of a goal (the criteria array item).
type Criterion struct {
	// Criterion id, unique within the goal; the stable handle an artifact's relates[].crit points at.
	ID string `json:"id"`
	// The criterion in one line — a checkable outcome, e.g. 'goal + goal.update lexicons land on v0.5'.
	Text string `json:"text"`
	// One of: met (satisfied; invariant — has >=1 proof-kind artifact in relates) | in-progress (actively being worked) | waiting-on-you (soft wait on a person) | blocked (HARD blocked, needs help) | not-started. Who flips it is fuzzy and uncoded: a mechanically-testable criterion self-serves (an agent runs it, writes a proof artifact, flips it); an agent may infer a human-approved artifact means met; or the operator sets it directly.
	Status string `json:"status"`
	// Optional agent accountable for this criterion (convenience label, not an assignment — signal, not manage).
	Owner string `json:"owner,omitempty"`
}

// Goal is the goal record (protocol/lexicons/goal.json): a north-star plus its acceptance criteria. Goal STATUS is derived from the criteria rollup, never stored — see Status in goals.go.
type Goal struct {
	// The objective in one line — what 'done' looks like, e.g. 'Ship v0.5.0 with the goal primitive'.
	Northstar string `json:"northstar"`
	// Optional grouping label so related goals read together in a UI (e.g. 'v0.5', 'hardening'). A free label, opaque to the bus.
	Stream string `json:"stream,omitempty"`
	// The acceptance criteria that define the goal. The goal's status is DERIVED from these (how many are met of the total) — there is no separate stored state field. An empty list reads as not-started.
	Criteria []Criterion `json:"criteria"`
	// ISO-8601 timestamp of this update.
	Updated string `json:"updated,omitempty"`
	// Who last set it (convenience label; the bus-stamped author of the artifact write is authoritative).
	By string `json:"by,omitempty"`
}
