// Package docgen renders the mdbook reference's generated pages from canon:
// the protocol surface (protocol/methods.json + protocol/lexicons/*.json), the
// backend-neutral implementer docs (protocol/semantic-contract.md and
// protocol/wire-api.md), and the Go SDK API (go/doc over pkg/sextant).
//
// It writes only the generated pages under docs/book/src/; the hand-written
// prose pages are never touched. Output is deterministic so the mdbook CI job
// can regenerate and fail on any diff — the docs cannot silently drift from the
// canon they are generated from (the same up-to-date guard the TS codegen uses).
package docgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// Run regenerates every generated page. root is the repo root; if empty, it is
// located by walking up from the working directory to the go.mod.
func Run(root string) error {
	if root == "" {
		r, err := findRoot()
		if err != nil {
			return err
		}
		root = r
	}
	pages := []struct {
		rel     string
		content func(string) (string, error)
	}{
		{"protocol/operations.md", genOperations},
		{"protocol/lexicons.md", genRecordLexicons},
		{"protocol/frame.md", genFrame},
		{"protocol/registry.md", genRegistry},
		{"implementers/backend.md", genBackend},
		{"implementers/wire-api.md", genWireAPI},
		{"sdk-go/reference.md", genSDKReference},
		{"sdk-go/messages.md", genSDKMessages},
		{"sdk-go/artifacts.md", genSDKArtifacts},
		{"sdk-go/clients.md", genSDKClients},
	}
	for _, p := range pages {
		body, err := p.content(root)
		if err != nil {
			return fmt.Errorf("%s: %w", p.rel, err)
		}
		out := filepath.Join(root, "docs", "book", "src", filepath.FromSlash(p.rel))
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(out, []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("docgen: go.mod not found above %s", dir)
		}
		dir = parent
	}
}

// header is the banner every generated page opens with: an HTML comment (the
// drift-check identity, invisible in the rendered book) plus a visible
// provenance note under the title.
func header(source string) string {
	return fmt.Sprintf("<!-- Code generated by cmd/docgen from %s; DO NOT EDIT. -->\n", source)
}

func provenance(source string) string {
	return fmt.Sprintf("> *Generated from `%s` — edit the source, then run `make book`.*\n", source)
}

// --- protocol/operations.md -------------------------------------------------

func genOperations(root string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(root, "protocol", "methods.json"))
	if err != nil {
		return "", err
	}
	var doc struct {
		Comment    string `json:"$comment"`
		Operations []struct {
			Name     string          `json:"name"`
			Summary  string          `json:"summary"`
			Delivery string          `json:"delivery"`
			Input    json.RawMessage `json:"input"`
			Output   json.RawMessage `json:"output"`
		} `json:"operations"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(header("protocol/methods.json"))
	b.WriteString("\n# Operations\n\n")
	b.WriteString(provenance("protocol/methods.json"))
	b.WriteString("\n")
	if doc.Comment != "" {
		b.WriteString("> " + strings.TrimSpace(doc.Comment) + "\n\n")
	}
	for _, op := range doc.Operations {
		fmt.Fprintf(&b, "## `%s`\n\n", op.Name)
		fmt.Fprintf(&b, "**Delivery:** %s\n\n", op.Delivery)
		if op.Summary != "" {
			b.WriteString(op.Summary + "\n\n")
		}
		in, err := fieldTable(op.Input)
		if err != nil {
			return "", err
		}
		out, err := fieldTable(op.Output)
		if err != nil {
			return "", err
		}
		b.WriteString("**Input**\n\n" + in + "\n")
		b.WriteString("**Output**\n\n" + out + "\n")
	}
	return b.String(), nil
}

// fieldTable renders a methods.json input/output object (field -> type-hint
// string) as a markdown table, preserving the authored field order.
func fieldTable(raw json.RawMessage) (string, error) {
	pairs, err := orderedPairs(raw)
	if err != nil {
		return "", err
	}
	if len(pairs) == 0 {
		return "_None._\n", nil
	}
	var b strings.Builder
	b.WriteString("| Field | Type |\n|---|---|\n")
	for _, p := range pairs {
		var hint string
		if err := json.Unmarshal(p.Val, &hint); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "| `%s` | %s |\n", p.Key, cell(hint))
	}
	return b.String(), nil
}

// --- lexicon pages ----------------------------------------------------------

func genRecordLexicons(root string) (string, error) {
	var b strings.Builder
	b.WriteString(header("protocol/lexicons/*.json"))
	b.WriteString("\n# Records & lexicons\n\n")
	b.WriteString(provenance("protocol/lexicons/*.json"))
	b.WriteString("\nA **record** is the typed content a client supplies; its type is a *lexicon* " +
		"(the schema, named on the record itself). These are the record lexicons a client " +
		"publishes or stores. The bus-space lexicons — the [frame](frame.md) and the " +
		"[client directory entry](registry.md) — are documented on their own pages.\n\n")
	for _, f := range []string{"chat.message.json", "document.json"} {
		sec, err := renderLexicon(root, f, 2)
		if err != nil {
			return "", err
		}
		b.WriteString(sec)
	}
	return b.String(), nil
}

func genFrame(root string) (string, error) {
	var b strings.Builder
	b.WriteString(header("protocol/lexicons/frame.json"))
	b.WriteString("\n# The frame\n\n")
	b.WriteString(provenance("protocol/lexicons/frame.json"))
	b.WriteString("\n")
	sec, err := renderLexicon(root, "frame.json", 0)
	if err != nil {
		return "", err
	}
	b.WriteString(sec)
	return b.String(), nil
}

func genRegistry(root string) (string, error) {
	var b strings.Builder
	b.WriteString(header("protocol/lexicons/client.json"))
	b.WriteString("\n# Clients registry & presence\n\n")
	b.WriteString(provenance("protocol/lexicons/client.json"))
	b.WriteString("\n")
	sec, err := renderLexicon(root, "client.json", 0)
	if err != nil {
		return "", err
	}
	b.WriteString(sec)
	return b.String(), nil
}

// renderLexicon renders one lexicon file. depth 0 renders the description and
// field table inline (one lexicon per page); depth >0 renders an `id` heading
// at that level first (many lexicons per page).
func renderLexicon(root, file string, depth int) (string, error) {
	raw, err := os.ReadFile(filepath.Join(root, "protocol", "lexicons", file))
	if err != nil {
		return "", err
	}
	var lf struct {
		ID   string `json:"id"`
		Defs struct {
			Main json.RawMessage `json:"main"`
		} `json:"defs"`
	}
	if err := json.Unmarshal(raw, &lf); err != nil {
		return "", err
	}
	var main struct {
		Description string          `json:"description"`
		Record      json.RawMessage `json:"record"`
		Required    []string        `json:"required"`
		Properties  json.RawMessage `json:"properties"`
	}
	if err := json.Unmarshal(lf.Defs.Main, &main); err != nil {
		return "", err
	}
	desc := main.Description
	required := main.Required
	properties := main.Properties
	if len(bytes.TrimSpace(main.Record)) > 0 {
		var rec struct {
			Required   []string        `json:"required"`
			Properties json.RawMessage `json:"properties"`
		}
		if err := json.Unmarshal(main.Record, &rec); err != nil {
			return "", err
		}
		required = rec.Required
		properties = rec.Properties
	}

	var b strings.Builder
	if depth > 0 {
		fmt.Fprintf(&b, "%s `%s`\n\n", strings.Repeat("#", depth), lf.ID)
	}
	if desc != "" {
		b.WriteString(strings.TrimSpace(desc) + "\n\n")
	}
	tbl, err := propertyTable(properties, required)
	if err != nil {
		return "", err
	}
	b.WriteString(tbl + "\n")
	return b.String(), nil
}

// propertyTable renders a lexicon properties object as a markdown table,
// preserving authored property order.
func propertyTable(raw json.RawMessage, required []string) (string, error) {
	pairs, err := orderedPairs(raw)
	if err != nil {
		return "", err
	}
	if len(pairs) == 0 {
		return "_No fields._\n", nil
	}
	req := make(map[string]bool, len(required))
	for _, r := range required {
		req[r] = true
	}
	var b strings.Builder
	b.WriteString("| Field | Type | Required | Description |\n|---|---|---|---|\n")
	for _, p := range pairs {
		var pv struct {
			Type        string   `json:"type"`
			Description string   `json:"description"`
			KnownValues []string `json:"knownValues"`
			Format      string   `json:"format"`
		}
		if err := json.Unmarshal(p.Val, &pv); err != nil {
			return "", err
		}
		typ := pv.Type
		if pv.Format != "" {
			typ += fmt.Sprintf(" (%s)", pv.Format)
		}
		if len(pv.KnownValues) > 0 {
			typ += " · one of: " + strings.Join(pv.KnownValues, ", ")
		}
		yes := ""
		if req[p.Key] {
			yes = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", p.Key, cell(typ), yes, cell(pv.Description))
	}
	return b.String(), nil
}

// --- implementer pages (render existing canon markdown) ---------------------

func genBackend(root string) (string, error) {
	return renderCanonMarkdown(root, "protocol/semantic-contract.md")
}

func genWireAPI(root string) (string, error) {
	return renderCanonMarkdown(root, "protocol/wire-api.md")
}

// renderCanonMarkdown wraps an already-prose canon markdown file with the
// generated-page banner and provenance note, leaving its body verbatim.
func renderCanonMarkdown(root, rel string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		return "", err
	}
	body := string(raw)
	// Insert the provenance note just after the title's first H1 line.
	var b strings.Builder
	b.WriteString(header(rel))
	lines := strings.SplitN(body, "\n", 2)
	b.WriteString("\n" + lines[0] + "\n\n")
	b.WriteString(provenance(rel))
	if len(lines) > 1 {
		b.WriteString("\n" + lines[1])
	}
	if !strings.HasSuffix(b.String(), "\n") {
		b.WriteString("\n")
	}
	return b.String(), nil
}

// --- Go SDK pages (go/doc over pkg/sextant) ---------------------------------

func genSDKReference(root string) (string, error) {
	d, fset, err := loadSDKDoc(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(header("pkg/sextant (go doc)"))
	b.WriteString("\n# API reference\n\n")
	b.WriteString(provenance("pkg/sextant (go doc)"))
	b.WriteString("\n")
	rend := commentRenderer(d)
	if dd := rend(d.Doc); dd != "" {
		b.WriteString(dd + "\n\n")
	}
	for _, f := range d.Funcs {
		b.WriteString(renderFunc(fset, f, 2, rend))
	}
	for _, t := range d.Types {
		b.WriteString(renderType(fset, t, 2, true, rend))
	}
	return b.String(), nil
}

func genSDKMessages(root string) (string, error) {
	return renderSDKArea(root, "Messages",
		"Publishing and reading typed messages over the bus.",
		[]string{
			"Message", "Handler", "Subscription", "SubOption", "DeliverAll",
			"Client.Publish", "Client.FetchMessages", "Client.Subscribe",
		})
}

func genSDKArtifacts(root string) (string, error) {
	return renderSDKArea(root, "Artifacts",
		"Creating, reading, and watching named, versioned shared work.",
		[]string{
			"Artifact", "ArtifactChange", "Watch",
			"Client.CreateArtifact", "Client.UpdateArtifact", "Client.GetArtifact",
			"Client.DeleteArtifact", "Client.WatchArtifact",
		})
}

func genSDKClients(root string) (string, error) {
	return renderSDKArea(root, "Clients & identity",
		"Listing the clients directory, and issuing or retiring identities.",
		[]string{
			"ClientInfo", "Issuer", "IssuedClient", "ConnectIssuer",
			"Client.ListClients", "Issuer.Register", "Issuer.Retire", "Issuer.ListClients",
		})
}

func renderSDKArea(root, title, intro string, symbols []string) (string, error) {
	d, fset, err := loadSDKDoc(root)
	if err != nil {
		return "", err
	}
	idx := indexDoc(d)
	var b strings.Builder
	b.WriteString(header("pkg/sextant (go doc)"))
	fmt.Fprintf(&b, "\n# %s\n\n", title)
	b.WriteString(provenance("pkg/sextant (go doc)"))
	b.WriteString("\n" + intro + "\n\n")
	rend := commentRenderer(d)
	for _, name := range symbols {
		s, ok := renderSymbol(fset, idx, name, rend)
		if !ok {
			return "", fmt.Errorf("symbol %q not found in pkg/sextant", name)
		}
		b.WriteString(s)
	}
	return b.String(), nil
}

// commentRenderer renders a Go doc comment string to markdown via go/doc/comment,
// which escapes text that would otherwise be read as markdown or HTML (e.g. the
// `<id>` / `<sub>` placeholders in subject patterns) and renders lists and links.
func commentRenderer(d *doc.Package) func(string) string {
	parser := d.Parser()
	pr := &comment.Printer{}
	return func(text string) string {
		if strings.TrimSpace(text) == "" {
			return ""
		}
		return strings.TrimSpace(string(pr.Markdown(parser.Parse(text))))
	}
}

func loadSDKDoc(root string) (*doc.Package, *token.FileSet, error) {
	fset := token.NewFileSet()
	dir := filepath.Join(root, "pkg", "sextant")
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil, nil, err
	}
	astPkg, ok := pkgs["sextant"]
	if !ok {
		return nil, nil, fmt.Errorf("package sextant not found in %s", dir)
	}
	d := doc.New(astPkg, "github.com/love-lena/sextant/pkg/sextant", 0)
	return d, fset, nil
}

type docIndex struct {
	types   map[string]*doc.Type
	funcs   map[string]*doc.Func
	methods map[string]*doc.Func // "Recv.Name"
}

func indexDoc(d *doc.Package) docIndex {
	idx := docIndex{
		types:   map[string]*doc.Type{},
		funcs:   map[string]*doc.Func{},
		methods: map[string]*doc.Func{},
	}
	for _, f := range d.Funcs {
		idx.funcs[f.Name] = f
	}
	for _, t := range d.Types {
		idx.types[t.Name] = t
		for _, f := range t.Funcs {
			idx.funcs[f.Name] = f
		}
		for _, m := range t.Methods {
			idx.methods[m.Recv+"."+m.Name] = m
			idx.methods[strings.TrimPrefix(m.Recv, "*")+"."+m.Name] = m
		}
	}
	return idx
}

func renderSymbol(fset *token.FileSet, idx docIndex, name string, rend func(string) string) (string, bool) {
	if strings.Contains(name, ".") {
		if m, ok := idx.methods[name]; ok {
			return renderFunc(fset, m, 2, rend), true
		}
		return "", false
	}
	if t, ok := idx.types[name]; ok {
		return renderType(fset, t, 2, false, rend), true
	}
	if f, ok := idx.funcs[name]; ok {
		return renderFunc(fset, f, 2, rend), true
	}
	return "", false
}

func renderType(fset *token.FileSet, t *doc.Type, level int, withMembers bool, rend func(string) string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s type `%s`\n\n", strings.Repeat("#", level), t.Name)
	b.WriteString(codeBlock(declString(fset, t.Decl)))
	if d := rend(t.Doc); d != "" {
		b.WriteString(d + "\n\n")
	}
	if withMembers {
		for _, f := range t.Funcs {
			b.WriteString(renderFunc(fset, f, level+1, rend))
		}
		for _, m := range t.Methods {
			b.WriteString(renderFunc(fset, m, level+1, rend))
		}
	}
	return b.String()
}

func renderFunc(fset *token.FileSet, f *doc.Func, level int, rend func(string) string) string {
	var b strings.Builder
	label := f.Name
	if f.Recv != "" {
		label = "(" + f.Recv + ") " + f.Name
	}
	fmt.Fprintf(&b, "%s func `%s`\n\n", strings.Repeat("#", level), label)
	b.WriteString(codeBlock(funcSignature(fset, f.Decl)))
	if d := rend(f.Doc); d != "" {
		b.WriteString(d + "\n\n")
	}
	return b.String()
}

// funcSignature prints a func declaration without its body.
func funcSignature(fset *token.FileSet, decl *ast.FuncDecl) string {
	if decl == nil {
		return ""
	}
	sig := *decl
	sig.Body = nil
	sig.Doc = nil
	return declString(fset, &sig)
}

func declString(fset *token.FileSet, node ast.Node) string {
	if node == nil {
		return ""
	}
	if gd, ok := node.(*ast.GenDecl); ok {
		clone := *gd
		clone.Doc = nil
		node = &clone
	}
	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 4}
	_ = cfg.Fprint(&buf, fset, node)
	return buf.String()
}

func codeBlock(code string) string {
	code = strings.TrimRight(code, "\n")
	if code == "" {
		return ""
	}
	return "```go\n" + code + "\n```\n\n"
}

// --- shared helpers ---------------------------------------------------------

type pair struct {
	Key string
	Val json.RawMessage
}

// orderedPairs decodes a JSON object preserving key order.
func orderedPairs(raw json.RawMessage) ([]pair, error) {
	if len(bytes.TrimSpace(raw)) == 0 {
		return nil, nil
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	if d, ok := tok.(json.Delim); !ok || d != '{' {
		return nil, fmt.Errorf("expected JSON object, got %v", tok)
	}
	var out []pair
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return nil, err
		}
		key, ok := keyTok.(string)
		if !ok {
			return nil, fmt.Errorf("expected string key, got %v", keyTok)
		}
		var val json.RawMessage
		if err := dec.Decode(&val); err != nil {
			return nil, err
		}
		out = append(out, pair{key, val})
	}
	return out, nil
}

// cell makes a string safe for a single markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}
