// Code generated by conventions/goal/ts/tools/lexgen.ts from
// protocol/lexicons/goal.json. DO NOT EDIT.
//
// The record types are generated so they cannot silently drift from the
// lexicon contract (ADR-0041) — the peer of the Go generator
// (conventions/goal/go/internal/lexgen). Regenerate with
// `npm run generate` after editing the lexicon; the verb logic that uses
// these types is hand-written in src/goals.ts.

// Criterion is one acceptance criterion of a goal (the criteria array item).
export interface Criterion {
  // Criterion id, unique within the goal; the stable handle an artifact's relates[].crit points at.
  id: string;
  // The criterion in one line — a checkable outcome, e.g. 'goal + goal.update lexicons land on v0.5'.
  text: string;
  // One of: met (satisfied; invariant — has >=1 proof-kind artifact in relates) | in-progress (actively being worked) | waiting-on-you (soft wait on a person) | blocked (HARD blocked, needs help) | not-started. Who flips it is fuzzy and uncoded: a mechanically-testable criterion self-serves (an agent runs it, writes a proof artifact, flips it); an agent may infer a human-approved artifact means met; or the operator sets it directly.
  status: string;
  // Optional agent accountable for this criterion (convenience label, not an assignment — signal, not manage).
  owner?: string;
}

// Goal is the goal record (protocol/lexicons/goal.json): a north-star plus its acceptance criteria. Goal STATUS is derived from the criteria rollup, never stored — see the read side in goals.ts.
export interface Goal {
  // The objective in one line — what 'done' looks like, e.g. 'Ship v0.5.0 with the goal primitive'.
  northstar: string;
  // Optional grouping label so related goals read together in a UI (e.g. 'v0.5', 'hardening'). A free label, opaque to the bus.
  stream?: string;
  // The acceptance criteria that define the goal. The goal's status is DERIVED from these (how many are met of the total) — there is no separate stored state field. An empty list reads as not-started.
  criteria: Criterion[];
  // ISO-8601 timestamp of this update.
  updated?: string;
  // Who last set it (convenience label; the bus-stamped author of the artifact write is authoritative).
  by?: string;
}
