package client_test

import (
	"context"
	"encoding/json"
	"errors"
	"sync"
	"testing"
	"time"

	"github.com/nats-io/nats.go"

	"github.com/love-lena/sextant/pkg/client"
	"github.com/love-lena/sextant/pkg/sextantproto"
)

// fakeRPCServer is a minimal NATS-side responder that handles a single
// verb without bringing pkg/rpc.Server into the client tests. Each
// helper here mirrors one rpc-catalog wire-semantics contract so the
// client surface can be exercised without a full daemon.
type fakeRPCServer struct {
	nc   *nats.Conn
	verb string
	mu   sync.Mutex
	hits int
}

// reply runs handler against each incoming request envelope. handler
// receives the request and returns the bytes to publish on req.ReplyTo
// (an rpc_response envelope, marshalled).
func (f *fakeRPCServer) reply(t *testing.T, handler func(req sextantproto.Envelope) sextantproto.RPCResponse) *nats.Subscription {
	t.Helper()
	sub, err := f.nc.Subscribe("sextant.rpc."+f.verb, func(msg *nats.Msg) {
		f.mu.Lock()
		f.hits++
		f.mu.Unlock()
		var req sextantproto.Envelope
		if err := json.Unmarshal(msg.Data, &req); err != nil {
			t.Errorf("fakeRPCServer: bad envelope: %v", err)
			return
		}
		reply := derefString(req.ReplyTo)
		if reply == "" {
			reply = msg.Reply
		}
		resp := handler(req)
		payload, err := json.Marshal(resp)
		if err != nil {
			t.Errorf("fakeRPCServer: marshal payload: %v", err)
			return
		}
		respEnv := req.Child(sextantproto.KindRPCResponse,
			sextantproto.Address{Kind: sextantproto.AddressDaemon, ID: "fake"},
			payload,
		)
		out, err := json.Marshal(respEnv)
		if err != nil {
			t.Errorf("fakeRPCServer: marshal envelope: %v", err)
			return
		}
		if err := f.nc.Publish(reply, out); err != nil {
			t.Errorf("fakeRPCServer: publish: %v", err)
		}
	})
	if err != nil {
		t.Fatalf("fakeRPCServer subscribe: %v", err)
	}
	t.Cleanup(func() { _ = sub.Unsubscribe() })
	return sub
}

func (f *fakeRPCServer) Hits() int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.hits
}

func derefString(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// TestRPCRoundTripsTypedReply is the read-back acceptance for the
// client's RPC method: marshal a request, get a structured reply.
func TestRPCRoundTripsTypedReply(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	type echoArgs struct{ Msg string }
	type echoReply struct{ Echo string }

	f := &fakeRPCServer{nc: cli.Conn(), verb: "echo"}
	f.reply(t, func(req sextantproto.Envelope) sextantproto.RPCResponse {
		var args echoArgs
		_ = json.Unmarshal(req.Payload, &args)
		result, _ := json.Marshal(echoReply{Echo: "echo:" + args.Msg})
		return sextantproto.RPCResponse{Result: result, Terminal: true}
	})

	var got echoReply
	if err := cli.RPC(ctx, "echo", echoArgs{Msg: "hello"}, &got); err != nil {
		t.Fatalf("RPC: %v", err)
	}
	if got.Echo != "echo:hello" {
		t.Fatalf("Echo = %q", got.Echo)
	}
}

// TestRPCSurfacesServerErrorAsRPCError pins the wire-semantics rule:
// a structured server error must reach the caller as a *RPCError so
// errors.As works.
func TestRPCSurfacesServerErrorAsRPCError(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	f := &fakeRPCServer{nc: cli.Conn(), verb: "explode"}
	f.reply(t, func(_ sextantproto.Envelope) sextantproto.RPCResponse {
		return sextantproto.RPCResponse{
			Error: &sextantproto.RPCError{
				Code:    sextantproto.ErrCodeAgentNotFound,
				Message: "no such agent",
			},
			Terminal: true,
		}
	})

	err := cli.RPC(ctx, "explode", nil, nil)
	if err == nil {
		t.Fatal("RPC must return an error")
	}
	var rerr *client.RPCError
	if !errors.As(err, &rerr) {
		t.Fatalf("err = %v, want *client.RPCError", err)
	}
	if rerr.Code != sextantproto.ErrCodeAgentNotFound {
		t.Fatalf("Code = %q, want %q", rerr.Code, sextantproto.ErrCodeAgentNotFound)
	}
}

// TestRPCTimeoutOnNoResponder asserts ErrRPCTimeout fires when no
// server is listening. The previous milestone (M4) used a
// not-implemented sentinel for the same "fail fast, never silently
// empty" invariant — this is the M7 replacement.
func TestRPCTimeoutOnNoResponder(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	err := cli.RPC(ctx, "no_one_listens", nil, nil, client.WithTimeout(300*time.Millisecond))
	if !errors.Is(err, client.ErrRPCTimeout) {
		t.Fatalf("err = %v, want ErrRPCTimeout", err)
	}
}

// TestRPCIdempotencyKeyIsAutoGenerated checks that consecutive calls
// without WithIdempotencyKey carry distinct keys (so the server-side
// cache treats them as separate requests, not replays).
func TestRPCIdempotencyKeyIsAutoGenerated(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	keys := make([]string, 0, 2)
	var keysMu sync.Mutex
	f := &fakeRPCServer{nc: cli.Conn(), verb: "idem_auto"}
	f.reply(t, func(req sextantproto.Envelope) sextantproto.RPCResponse {
		keysMu.Lock()
		keys = append(keys, derefString(req.IdempotencyKey))
		keysMu.Unlock()
		return sextantproto.RPCResponse{Result: json.RawMessage(`{}`), Terminal: true}
	})

	for i := 0; i < 2; i++ {
		if err := cli.RPC(ctx, "idem_auto", nil, nil); err != nil {
			t.Fatalf("RPC[%d]: %v", i, err)
		}
	}
	keysMu.Lock()
	defer keysMu.Unlock()
	if len(keys) != 2 {
		t.Fatalf("got %d hits, want 2", len(keys))
	}
	if keys[0] == "" || keys[1] == "" {
		t.Fatalf("auto-generated keys must be non-empty, got %v", keys)
	}
	if keys[0] == keys[1] {
		t.Fatalf("auto-generated keys must differ, got %q twice", keys[0])
	}
}

// TestRPCWithIdempotencyKeyOverride pins the option contract: the
// caller-supplied key reaches the server unchanged.
func TestRPCWithIdempotencyKeyOverride(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	var seen string
	var mu sync.Mutex
	f := &fakeRPCServer{nc: cli.Conn(), verb: "idem_pin"}
	f.reply(t, func(req sextantproto.Envelope) sextantproto.RPCResponse {
		mu.Lock()
		seen = derefString(req.IdempotencyKey)
		mu.Unlock()
		return sextantproto.RPCResponse{Result: json.RawMessage(`{}`), Terminal: true}
	})

	const pin = "00000000-0000-0000-0000-000000000001"
	if err := cli.RPC(ctx, "idem_pin", nil, nil, client.WithIdempotencyKey(pin)); err != nil {
		t.Fatalf("RPC: %v", err)
	}
	mu.Lock()
	defer mu.Unlock()
	if seen != pin {
		t.Fatalf("server saw %q, want %q", seen, pin)
	}
}

// TestPublishValidatesEnvelope guards the "TraceID is required" rule
// on the publish path.
func TestPublishValidatesEnvelope(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	// Build a deliberately-broken envelope: no trace_id.
	env := sextantproto.Envelope{
		ProtoVersion: sextantproto.ProtoVersion,
		From:         sextantproto.Address{Kind: sextantproto.AddressOperator, ID: "lena"},
		Kind:         sextantproto.KindAgentFrame,
	}
	err := cli.Publish(ctx, "agents.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.frames", env)
	if err == nil {
		t.Fatal("Publish must reject an invalid envelope")
	}
}

// TestPublishRoundTripsToSubscriber publishes a valid envelope and
// asserts the bus delivers it to a subscriber over JetStream.
func TestPublishRoundTripsToSubscriber(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	subject := "agents.cccccccc-1111-2222-3333-444444444444.frames"
	ch, err := cli.Subscribe(ctx, subject)
	if err != nil {
		t.Fatalf("Subscribe: %v", err)
	}
	env, err := sextantproto.NewEnvelopeWith(
		sextantproto.KindAgentFrame,
		sextantproto.Address{Kind: sextantproto.AddressAgent, ID: "cccccccc-1111-2222-3333-444444444444"},
		map[string]string{"hello": "publish"},
	)
	if err != nil {
		t.Fatalf("NewEnvelopeWith: %v", err)
	}
	if err := cli.Publish(ctx, subject, env); err != nil {
		t.Fatalf("Publish: %v", err)
	}
	select {
	case m := <-ch:
		if m.Err != nil {
			t.Fatalf("got Message.Err = %v", m.Err)
		}
		if m.Envelope.ID != env.ID {
			t.Fatalf("envelope id = %s, want %s", m.Envelope.ID, env.ID)
		}
	case <-time.After(10 * time.Second):
		t.Fatal("timed out waiting for published envelope")
	}
}

// TestPutKVStoresAndGetsBack rounds out the KV trio. M4 shipped GetKV
// + WatchKV; M7 closes the write side.
func TestPutKVStoresAndGetsBack(t *testing.T) {
	srv := bootedServer(t)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cli := clientFromServer(ctx, t, srv)

	if err := cli.PutKV(ctx, "ui_state", "test.key", []byte("v1")); err != nil {
		t.Fatalf("PutKV: %v", err)
	}
	got, err := cli.GetKV(ctx, "ui_state", "test.key")
	if err != nil {
		t.Fatalf("GetKV: %v", err)
	}
	if string(got) != "v1" {
		t.Fatalf("Get value = %q, want v1", got)
	}
	// Overwrite.
	if err := cli.PutKV(ctx, "ui_state", "test.key", []byte("v2")); err != nil {
		t.Fatalf("PutKV (overwrite): %v", err)
	}
	got2, err := cli.GetKV(ctx, "ui_state", "test.key")
	if err != nil {
		t.Fatalf("GetKV (after overwrite): %v", err)
	}
	if string(got2) != "v2" {
		t.Fatalf("Get value after overwrite = %q, want v2", got2)
	}
}
